// product state
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS'
export const OBTENER_PRODUCTOS_SUCCESS = 'OBTENER_PRODUCTOS_SUCCESS'

// pedido state
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'
export const CONFIRMAR_ORDEN = 'CONFIRMAR_ORDEN'
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN'
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'
export const PEDIDO_ORDENADO = 'PEDIDO_ORDENADO'