// product state
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS'
export const OBTENER_PRODUCTOS_SUCCESS = 'OBTENER_PRODUCTOS_SUCCESS'

// pedido state
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'
export const CONFIRMAR_ORDEN = 'CONFIRMAR_ORDEN'